# Generated by Django 2.1.4 on 2018-12-15 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('D', 'Denied')], max_length=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 15, 19, 10, 7, 426692))),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_from', to=settings.AUTH_USER_MODEL)),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
